# =====================================================================
# Crossplane XRD — CompositeResourceDefinition
# =====================================================================
# TODO 2: Completa este archivo con tu XRD
#
# Guía de referencia:
#   https://docs.crossplane.io/latest/concepts/composite-resource-definitions/
#
# Este XRD debe:
#   - Definir un Composite Resource llamado XPostgreSQLInstance
#   - Exponer al menos 2 parámetros (ej: dbName, owner)
#   - Usar el grupo database.poc.io/v1alpha1
# =====================================================================

apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: postgresqlinstances.database.poc.io
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
spec:
  group: database.poc.io
  scope: Cluster
  names:
    kind: XPostgreSQLInstance
    plural: postgresqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbName:
                  type: string
                owner:
                  type: string
              required:
                - dbName

